### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [nix-community/nixpkgs-swh#3]
Hi:
what would be the license for this repo?
Thanks!

**Comment by nlewo** [comment]
I generally use the MIT license on my projects but I'm open to other choices. Do you have any specific license in mind?

**Comment by pombredanne** [comment]
@nlewo your MIT pick or any open source license you can pick is good! No license is a problem ;)

**Comment by nlewo** [comment]
@jeremyschlatter I just realized i'm not the only contributor of this repository:/ 
Are you ok with https://github.com/nix-community/nixpkgs-swh/commit/5bff62c2bb38197adcec8e26f342f71a345d24a5 ?

**Comment by jeremyschlatter** [comment]
yep! 👍
